name: Flutter iOS Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS (Tanpa Signing)
    runs-on: ma+cos-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        # Menggunakan --no-codesign karena kita tidak punya sertifikat Apple
        run: flutter build ios --release --no-codesign --dart-define=GOOGLE_CLIENT_ID=861064220732-vcikg3u9lb7l1ub4it3i902nt599lh7n.apps.googleusercontent.com

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios/iphoneos/